--[[
    Author: https://github.com/Fernando-A-Rocha

    Collectibles - System [Testing] (Server)

    /!\ Unless you know what you are doing, do not edit this file. /!\
]]

-- TP to where the demo collectibles are spawned
addCommandHandler("bb", function(thePlayer)
    setElementPosition(thePlayer, 0, 0, 3)
    setElementInterior(thePlayer, 0)
    setElementDimension(thePlayer, 0)
end, false, false)
addCommandHandler("shop", function(thePlayer)
    setElementPosition(thePlayer, -30.99, -90.74, 1003.6)
    setElementInterior(thePlayer, 18)
    setElementDimension(thePlayer, 0)
end, false, false)

addCommandHandler("collectiblesdata", function(thePlayer, cmd, targetAccountID)
    if not canAdminCollectibles(thePlayer) then
        return outputChatBox("You do not have permission to use this command.", thePlayer, 255, 0, 0)
    end
    local targetAccount
    if targetAccountID then
        targetAccountID = tonumber(targetAccountID)
        if not targetAccountID then
            return outputChatBox("Invalid account ID.", thePlayer, 255, 0, 0)
        end
        targetAccount = getAccountByID(targetAccountID)
        if (not targetAccount) then
            return outputChatBox("Invalid account ID.", thePlayer, 255, 0, 0)
        end
        if isGuestAccount(targetAccount) then
            return outputChatBox("Account ID "..targetAccountID.." is not logged in.", thePlayer, 255, 0, 0)
        end
    else
        targetAccount = getPlayerAccount(thePlayer)
        if (not targetAccount) or isGuestAccount(targetAccount) then
            return outputChatBox("You are not logged in.", thePlayer, 255, 0, 0)
        end
    end
    local clientCountsDataName = getAccountDataNames().CLIENT_COUNTS
    local data = getAccountData(targetAccount, clientCountsDataName) or {}
    data = fromJSON(data)
    if not data then
        return outputChatBox("Corrupt JSON account data: "..clientCountsDataName, thePlayer, 255, 0, 0)
    end
    local c = 0
    for theType, v in pairs(data) do
        outputChatBox("Type: "..theType, thePlayer)
        for theID, timestamp in pairs(v) do
            local colDate = tonumber(timestamp)
            if colDate then
                colDate = os.date("%d/%m/%Y %H:%M:%S", colDate)
            else
                colDate = "Unknown"
            end
            outputChatBox("   spID: "..theID..", Collected at: "..colDate, thePlayer)
        end
        c = c + 1
    end
    if c == 0 then
        outputChatBox("No account data: "..clientCountsDataName, thePlayer, 255, 0, 0)
    end
end, false, false)
