--[[
    Author: https://github.com/Fernando-A-Rocha

    Collectibles - System (Shared)

    /!\ Unless you know what you are doing, do not edit this file. /!\
]]

function getCustomText(name, ...)
    local constants = getConstants()
    local info = constants.STRINGS[name]
    if type(info) ~= "table" or type(info.value) ~= "string" then
        return "[MISSING STRING '"..name.."']"
    end
    local text = info.value
    local r,g,b
    if type(info.rgb)=="table" and type(info.rgb[1]) == "number" and type(info.rgb[2]) == "number" and type(info.rgb[3]) == "number" then
        r,g,b = info.rgb[1], info.rgb[2], info.rgb[3]
    else
        r,g,b = 255, 255, 255
    end
    local formatWith = {...}
    if #formatWith > 0 then
        text = string.format(text, unpack(formatWith))
    end
    return text, r, g, b
end

if isElement(localPlayer) then
    -- Clientside version
    function outputCustomText(name, ...)
        local text, r, g, b = getCustomText(name, ...)
        if text then
            outputChatBox(text, r, g, b, true)
        end
    end
else
    -- Serverside version
    function outputCustomText(player, name, ...)
        local text, r, g, b = getCustomText(name, ...)
        if text then
            outputChatBox(text, player, r, g, b, true)
        end
    end
end