--[[
    Author: https://github.com/Fernando-A-Rocha

    Collectibles - System (Client)

    /!\ Unless you know what you are doing, do not edit this file. /!\
]]

-- Internal Events
addEvent("collectibles:receive", true) -- source: always the local player
addEvent("collectibles:despawn", true) -- source: always the local player
addEvent("collectibles:spawn", true) -- source: always the local player
addEvent("collectibles:actionOnPickedUp", true) -- source: always the local player
addEvent("collectibles:pickupDenied", true) -- source: always the local player

local SW, SH = guiGetScreenSize()

local receivedCollectibles = {}
local spawnedCollectibles = nil
local lastActionAt = nil
local drawing = nil
local waitingPickup = nil
local CONSTANTS = {}

function getConstants()
    return CONSTANTS
end
function outputDebugMsg(msg, theType)
    msg = "[Collectibles] " .. msg
    local r,g,b = 255, 255, 255
    if theType == "ERROR" then
        r,g,b = 255, 25, 25
    elseif theType == "WARNING" then
        r,g,b = 255, 255, 25
    end
    outputDebugString(msg, 4, r,g,b)
end

local function createOnePickup(theType, spID, spawnpoint)
    local pickup = createPickup(spawnpoint.x, spawnpoint.y, spawnpoint.z, 3, spawnpoint.model)
    if not pickup then
        outputDebugMsg("Failed to create pickup for type '" .. theType .. "' at spawnpoint " .. (spID) .. ".", "ERROR")
        return false
    end
    setElementInterior(pickup, spawnpoint.interior)
    setElementDimension(pickup, spawnpoint.dimension)
    spawnedCollectibles[pickup] = {
        type = theType,
        spID = spID,
    }
    return pickup
end

local function toggleCollectibles(theType)
    local info = receivedCollectibles[theType]
    if not info then
        return
    end
    if (not lastActionAt or getTickCount() - lastActionAt > 500) then
        lastActionAt = getTickCount()
    else
        return
    end
    local countAvailable = #info.spawnpoints
    local countCollected = info.total - countAvailable
    if countAvailable == 0 then
        outputCustomText("already_collected", (string.gsub(theType, "_", " ")), info.total)
        return
    end
    if receivedCollectibles[theType].toggled == false then
        -- Create collectibles
        for i=1, countAvailable do
            local spawnpoint = info.spawnpoints[i]
            if spawnpoint then
                createOnePickup(theType, spawnpoint.spID, spawnpoint)
            end
        end
        outputCustomText("toggle_on", countCollected, info.total, (string.gsub(theType, "_", " ")))
        receivedCollectibles[theType].toggled = true
    else
        -- Destroy collectibles
        local countDel = 0
        for pickup, info2 in pairs(spawnedCollectibles) do
            if info2.type == theType then
                destroyElement(pickup)
                countDel = countDel + 1
                spawnedCollectibles[pickup] = nil
            end
        end
        outputCustomText("toggle_off", countDel, (string.gsub(theType, "_", " ")))
        receivedCollectibles[theType].toggled = false
    end
end

local function createCollectibles(initial)
    for theType, info in pairs(receivedCollectibles) do
        if (info.toggled == true) then
            for i=1, #info.spawnpoints do
                local spawnpoint = info.spawnpoints[i]
                if spawnpoint then
                    createOnePickup(theType, spawnpoint.spID, spawnpoint)
                end
            end
        end
        if (initial == true) then
            if info.toggle_keybind then
                -- outputConsole("Keybind set: "..(string.upper(info.toggle_keybind)))
                bindKey(info.toggle_keybind, "down", function()
                    toggleCollectibles(theType)
                end)
            end
            if info.toggle_command then
                -- outputConsole("Command set: /"..info.toggle_command)
                addCommandHandler(info.toggle_command, function(cmd)
                    toggleCollectibles(theType)
                end, false)
            end
        end
    end
end

local function onPickupHit(thePlayer)
    if thePlayer ~= localPlayer then return end
    if not spawnedCollectibles then return end
    if waitingPickup ~= nil then return end
    local collectibleInfo = spawnedCollectibles[source]
    if not collectibleInfo then return end
    if (getElementDimension(localPlayer) ~= getElementDimension(source) or getElementInterior(localPlayer) ~= getElementInterior(source)) then return end
    local theType = collectibleInfo.type
    local spID = collectibleInfo.spID
    waitingPickup = {type = theType, spID = spID, pickup = source}
    triggerServerEvent("collectibles:handlePickedUp", root, false, collectibleInfo)
end
addEventHandler("onClientPickupHit", resourceRoot, onPickupHit)

addEventHandler("collectibles:pickupDenied", localPlayer, function(collectibleInfo)
    if waitingPickup == nil then return end
    if (waitingPickup.type ~= collectibleInfo.type or waitingPickup.spID ~= collectibleInfo.spID) then return end
    waitingPickup = nil
end, false)

local function drawCollectible()
    local elapsed = getTickCount() - drawing.startedAt
    if elapsed > 5000 then
        removeEventHandler("onClientRender", root, drawCollectible)
        drawing = nil
        return
    end

    local text_top = drawing.text_top
    local text_bottom = drawing.text_bottom

    local top_text = drawing.text_top_text
    local bottom_text = drawing.text_bottom_text

    local top_font, top_scale, top_alignX, top_alignY, top_color, top_x_left, top_y_top, top_x_right, top_y_bottom, top_outline_color = text_top.font, text_top.scale, text_top.alignX, text_top.alignY, text_top.color, text_top.x_left, text_top.y_top, text_top.x_right, text_top.y_bottom, text_top.outline_color
    local bottom_font, bottom_scale, bottom_alignX, bottom_alignY, bottom_color, bottom_x_left, bottom_y_top, bottom_x_right, bottom_y_bottom, bottom_outline_color = text_bottom.font, text_bottom.scale, text_bottom.alignX, text_bottom.alignY, text_bottom.color, text_bottom.x_left, text_bottom.y_top, text_bottom.x_right, text_bottom.y_bottom, text_bottom.outline_color

    if (top_outline_color) then
        dxDrawText(top_text, top_x_left+1, top_y_top+1, top_x_right + 1, top_y_bottom + 1, top_outline_color, top_scale, top_font, top_alignX, top_alignY, false, false, true, true)
        dxDrawText(top_text, top_x_left+1, top_y_top-1, top_x_right + 1, top_y_bottom - 1, top_outline_color, top_scale, top_font, top_alignX, top_alignY, false, false, true, true)
        dxDrawText(top_text, top_x_left-1, top_y_top+1, top_x_right - 1, top_y_bottom + 1, top_outline_color, top_scale, top_font, top_alignX, top_alignY, false, false, true, true)
        dxDrawText(top_text, top_x_left+1, top_y_top+1, top_x_right - 1, top_y_bottom - 1, top_outline_color, top_scale, top_font, top_alignX, top_alignY, false, false, true, true)
    end
    
    dxDrawText(top_text, top_x_left, top_y_top, top_x_right, top_y_bottom, top_color, top_scale, top_font, top_alignX, top_alignY, false, false, true, true)
    
    if (bottom_outline_color) then
        dxDrawText(bottom_text, bottom_x_left+1, bottom_y_top+1, bottom_x_right + 1, bottom_y_bottom + 1, bottom_outline_color, bottom_scale, bottom_font, bottom_alignX, bottom_alignY, false, false, true, true)
        dxDrawText(bottom_text, bottom_x_left+1, bottom_y_top-1, bottom_x_right + 1, bottom_y_bottom - 1, bottom_outline_color, bottom_scale, bottom_font, bottom_alignX, bottom_alignY, false, false, true, true)
        dxDrawText(bottom_text, bottom_x_left-1, bottom_y_top+1, bottom_x_right - 1, bottom_y_bottom + 1, bottom_outline_color, bottom_scale, bottom_font, bottom_alignX, bottom_alignY, false, false, true, true)
        dxDrawText(bottom_text, bottom_x_left+1, bottom_y_top+1, bottom_x_right - 1, bottom_y_bottom - 1, bottom_outline_color, bottom_scale, bottom_font, bottom_alignX, bottom_alignY, false, false, true, true)
    end

    dxDrawText(bottom_text, bottom_x_left, bottom_y_top, bottom_x_right, bottom_y_bottom, bottom_color, bottom_scale, bottom_font, bottom_alignX, bottom_alignY, false, false, true, true)
end

local function getDefaultOrCustomStyle(theType)
    local text_top, text_bottom
    if type(DRAWING_STYLES.DEFAULT)~="table" then
        outputDebugMsg("Failed to find default drawing style.", "ERROR")
    else
        local default = DRAWING_STYLES.DEFAULT
        local custom = DRAWING_STYLES.CUSTOM or {}
        custom = custom[theType] or {}
        local custom_top, custom_bottom = custom["text_top"], custom["text_bottom"]
        if custom_top then
            text_top = custom_top
        else
            text_top = default.text_top
        end
        if custom_bottom then
            text_bottom = custom_bottom
        else
            text_bottom = default.text_bottom
        end
    end
    return text_top, text_bottom
end

local function actionOnPickedUp(theType, collected, total, action)
    
    local sound = action.sound
    local sound_volume = action.sound_volume
    if sound then
        local soundElement = playSound(sound, false)
        if not soundElement then
            outputDebugMsg("Failed to play sound '" .. sound .. "'.", "ERROR")
        else
            setSoundVolume(soundElement, sound_volume)
        end
    end
    local text_top, text_bottom = getDefaultOrCustomStyle(theType)
    if text_top then
        local notDrawing = (drawing == nil)
        drawing = {
            startedAt = getTickCount(),
            text_top = text_top,
            text_top_text = text_top.text:format(string.gsub(theType, "_", " ")),
            text_bottom = text_bottom,
            text_bottom_text = text_bottom.text:format(collected, total),
        }
        if (notDrawing == true) then
            addEventHandler("onClientRender", root, drawCollectible)
        end
    end

    if waitingPickup and waitingPickup.type == theType then
        local theIndex
        for i=1, #receivedCollectibles[theType].spawnpoints do
            local sp = receivedCollectibles[theType].spawnpoints[i]
            if sp and sp.spID == waitingPickup.spID then
                theIndex = i
                break
            end
        end
        if theIndex then
            table.remove(receivedCollectibles[theType].spawnpoints, theIndex)
        else
            outputDebugMsg("Failed to find spawnpoint ID '" .. waitingPickup.spID .. "' of type '" .. theType .. "'.", "ERROR")
        end
        destroyElement(waitingPickup.pickup)
        spawnedCollectibles[waitingPickup.pickup] = nil
        waitingPickup = nil
    end
end
addEventHandler("collectibles:actionOnPickedUp", localPlayer, actionOnPickedUp, false)

addEventHandler("collectibles:receive", localPlayer, function(list, CONSTANTS_)
    if type(list) ~= "table" then
        return
    end
    receivedCollectibles = list
    CONSTANTS = CONSTANTS_

    local initial = true
    if type(spawnedCollectibles) == "table" then
        initial = false
        for pickup, info in pairs(spawnedCollectibles) do
            destroyElement(pickup)
        end
    end

    spawnedCollectibles = {}
    createCollectibles(initial)

end, false)

addEventHandler("collectibles:despawn", localPlayer, function()
    if type(spawnedCollectibles) ~= "table" then
        return
    end
    for pickup, info in pairs(spawnedCollectibles) do
        destroyElement(pickup)
    end
    spawnedCollectibles = nil
end, false)

addEventHandler("collectibles:spawn", localPlayer, function(theType, spID, spawnpoint)
    if not receivedCollectibles[theType] then
        return
    end
    if type(spawnpoint) ~= "table" then
        return
    end
    local theIndex = #receivedCollectibles[theType].spawnpoints + 1
    receivedCollectibles[theType].spawnpoints[spID] = {
        spID = spID,
        x = spawnpoint.x,
        y = spawnpoint.y,
        z = spawnpoint.z,
        model = spawnpoint.model,
    }

    if receivedCollectibles[theType].toggled ~= true then
        return
    end
    if createOnePickup(theType, spID, spawnpoint) then
        outputCustomText("respawned", (string.gsub(theType, "_", " ")), spID)
    end
end, false)

addEventHandler("onClientResourceStart", resourceRoot, function()
    triggerLatentServerEvent("collectibles:requestCollectibles", resourceRoot)
end, false)
