--[[
    Author: https://github.com/Fernando-A-Rocha

    Collectibles - System (Shared)

    /!\ Unless you know what you are doing, do not edit this file. /!\
]]

-- gct means getCustomText
function gct(name, ...)
    local formatWith = {...}
    local r, g, b = 255, 255, 255
    local constants = getConstants()
    local info = constants.STRINGS[name]
    if type(info) ~= "table" or type(info.value) ~= "string" then
        if #formatWith > 0 then
            name = string.format(name, unpack(formatWith))
        end
        return name, r, g, b
    end
    local text = info.value
    if type(info.rgb)=="table" and type(info.rgb[1]) == "number" and type(info.rgb[2]) == "number" and type(info.rgb[3]) == "number" then
        r, g, b = info.rgb[1], info.rgb[2], info.rgb[3]
    end
    if #formatWith > 0 then
        text = string.format(text, unpack(formatWith))
    end
    return text, r, g, b
end

-- oct means outputCustomText
if isElement(localPlayer) then
    -- Clientside version
    function oct(name, ...)
        local text, r, g, b = gct(name, ...)
        if text then
            outputChatBox(text, r, g, b, true)
        end
    end
else
    -- Serverside version
    function oct(player, name, ...)
        local text, r, g, b = gct(name, ...)
        if text then
            outputChatBox(text, player, r, g, b, true)
        end
    end
end

function isDefaultObjectID(id)
	if id < 321 or id > 18630 then
		return false
	end
	-- exclude unused/reserved for other purposes IDs
	if id >= 374 and id <= 614 then
		return false
	end
	if id >= 11682 and id <= 12799 then
		return false
	end
	if id >= 15065 and id <= 15999 then
		return false
	end
	return true
end

function outputDebugMsg(msg, theType)
    msg = "[Collectibles] " .. msg
    local r,g,b = 255, 255, 255
    if theType == "ERROR" then
        r,g,b = 255, 25, 25
    elseif theType == "WARNING" then
        r,g,b = 255, 255, 25
    end
    outputDebugString(msg, 4, r,g,b)
end
